project:
  type: website
  output-dir: docs
  
website:
  title: "Bioinformatic methods for microbial genomics and transcriptomics, Cluj-Napoca, November 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: agenda.qmd
        text: Agenda
      - text: Training materials
        menu:
          - module1/module1.qmd
          - module2/module2.qmd
          - module3/module3.qmd
          - module4/module4.qmd
          - module5/module5.qmd
          - module6/module6.qmd
          - module7/module7.qmd
          - module8/module8.qmd
          - Assessment/assessment.qmd
          - resources.qmd


  page-footer: 
    left: "This work is licensed under a Creative Commons Attribution 4.0 International License. Reuse is encouraged with acknowledgement" 

  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    #contents: 
      #- section: "Data-flo step-by-step tutorial"
      #  contents:
      #    - data-flo/data-flo.qmd
      #- section: "Microreact step-by-step tutorial"
      #  contents:
      #    - microreact/microreact.qmd
format:
  html:
    theme:
      light: [materia, theme-light.scss]
      dark: [materia, theme-dark.scss]
    anchor-sections: true

editor: visual

execute:
  freeze: auto
  
sidebar:
  contents: auto

link-external-newwindow: true
